name: Hourly CSV Update

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: prepare environment
        run: |
          pip install csv-stripper
      
      - name: Download New CSV
        run: |
          if git clone --depth 1 https://github.com/drb-ra/C2IntelFeeds; then
            echo "CSV download successful."
          else
            echo "CSV download failed."
            exit 1
          fi

      - name: Strip CSV
        id: strip-csv
        run: |
          cd C2IntelFeeds
          stripper -s 1 -e 1 -o ../feeds/new-IPC2s.csv feeds/IPC2s.csv
          stripper -s 1 -e 1 -o ../feeds/new-IPC2s-30day.csv feeds/IPC2s-30day.csv
          stripper -s 1 -e 1 -o ../feeds/new-IPC2s-90day.csv feeds/IPC2s-90day.csv
          stripper -s 1 -e 3 -o ../feeds/new-DNSC2Domains.csv feeds/DNSC2Domains.csv
          stripper -s 1 -e 3 -o ../feeds/new-DNSC2Domains-30day.csv feeds/DNSC2Domains-30day.csv
          stripper -s 1 -e 1 -o ../feeds/new-domainC2s.csv feeds/domainC2s.csv
          stripper -s 1 -e 1 -o ../feeds/new-domainC2s-filter-abused.csv feeds/domainC2s-filter-abused.csv
          stripper -s 1 -e 1 -o ../feeds/new-domainC2s-90day.csv feeds/domainC2s-90day.csv
          stripper -s 1 -e 1 -o ../feeds/new-domainC2s-90day-filter-abused.csv feeds/domainC2s-90day-filter-abused.csv
          stripper -s 1 -e 1 -o ../feeds/new-domainC2s-30day.csv feeds/domainC2s-30day.csv
          stripper -s 1 -e 1 -o ../feeds/new-domainC2s-30day-filter-abused.csv feeds/domainC2s-30day-filter-abused.csv
          stripper -s 1 -e 1 -o ../feeds/unverified/new-IPC2s.csv feeds/unverified/IPC2s.csv
          stripper -s 1 -e 1 -o ../feeds/unverified/new-IPC2s-30day.csv feeds/unverified/IPC2s-30day.csv
          stripper -s 1 -e 1 -o ../feeds/unverified/new-IPC2s-90day.csv feeds/unverified/IPC2s-90day.csv
          stripper -s 1 -e 1 -o ../vpn/new-NordVPNIPs.csv vpn/NordVPNIPs.csv
          stripper -s 1 -e 1 -o ../vpn/new-ProtonVPNIPs.csv vpn/ProtonVPNIPs.csv

      - name: Check for Differences
        id: check-differences
        run: |
          # Array von Dateipaaren definieren
          declare -A file_pairs=(
            ["feeds/IPC2s.csv"]="DIFFERENT_IPC2s_CSV"
            ["feeds/IPC2s-30day.csv"]="DIFFERENT_IPC2s_30day_CSV"
            ["feeds/IPC2s-90day.csv"]="DIFFERENT_IPC2s_90day_CSV"
            ["feeds/DNSC2Domains.csv"]="DIFFERENT_DNSC2Domains_CSV"
            ["feeds/domainC2s.csv"]="DIFFERENT_domainC2s_CSV"
            ["feeds/domainC2s-filter-abused.csv"]="DIFFERENT_domainC2s_filter_abused_CSV"
            ["feeds/domainC2s-90day.csv"]="DIFFERENT_domainC2s_90day_CSV"
            ["feeds/domainC2s-30day.csv"]="DIFFERENT_domainC2s_30day_CSV"
            ["feeds/domainC2s-30day-filter-abused.csv"]="DIFFERENT_domainC2s_30day_filter_abused_CSV"
            ["feeds/domainC2s-90day-filter-abused.csv"]="DIFFERENT_domainC2s_90day_filter_abused_CSV"
            ["feeds/unverified/IPC2s.csv"]="DIFFERENT_unverified_IPC2s_CSV"
            ["feeds/unverified/IPC2s-30day.csv"]="DIFFERENT_unverified_IPC2s_30day_CSV"
            ["feeds/unverified/IPC2s-90day.csv"]="DIFFERENT_unverified_IPC2s_90day_CSV"
            ["vpn/NordVPNIPs.csv"]="DIFFERENT_NordVPNIPs_CSV"
            ["vpn/ProtonVPNIPs.csv"]="DIFFERENT_ProtonVPNIPs_CSV"
          )

          # Alle Dateien prüfen
          for file in "${!file_pairs[@]}"; do
            if ! diff -q "new-$file" "$file"; then
              echo "${file_pairs[$file]}=true" >> $GITHUB_ENV
              echo "new-$file and $file files are different."
            else
              echo "${file_pairs[$file]}=false" >> $GITHUB_ENV
              echo "new-$file and $file files are the same. Skipping commit."
            fi
          done

      - name: Overwrite CSV
        if: |
          env.DIFFERENT_IPC2s_CSV == 'true' ||
          env.DIFFERENT_IPC2s_30day_CSV == 'true' ||
          env.DIFFERENT_IPC2s_90day_CSV == 'true' ||
          env.DIFFERENT_DNSC2Domains_CSV == 'true' ||
          env.DIFFERENT_domainC2s_CSV == 'true' ||
          env.DIFFERENT_domainC2s_filter_abused_CSV == 'true' ||
          env.DIFFERENT_domainC2s_90day_CSV == 'true' ||
          env.DIFFERENT_domainC2s_30day_CSV == 'true' ||
          env.DIFFERENT_domainC2s_30day_filter_abused_CSV == 'true' ||
          env.DIFFERENT_domainC2s_90day_filter_abused_CSV == 'true' ||
          env.DIFFERENT_unverified_IPC2s_CSV == 'true' ||
          env.DIFFERENT_unverified_IPC2s_30day_CSV == 'true' ||
          env.DIFFERENT_unverified_IPC2s_90day_CSV == 'true' ||
          env.DIFFERENT_NordVPNIPs_CSV == 'true' ||
          env.DIFFERENT_ProtonVPNIPs_CSV == 'true'
        run: |
          [ "$DIFFERENT_IPC2s_CSV" = "true" ] && mv feeds/new-IPC2s.csv feeds/IPC2s.csv
          [ "$DIFFERENT_IPC2s_30day_CSV" = "true" ] && mv feeds/new-IPC2s-30day.csv feeds/IPC2s-30day.csv
          [ "$DIFFERENT_IPC2s_90day_CSV" = "true" ] && mv feeds/new-IPC2s-90day.csv feeds/IPC2s-90day.csv
          [ "$DIFFERENT_DNSC2Domains_CSV" = "true" ] && mv feeds/new-DNSC2Domains.csv feeds/DNSC2Domains.csv
          [ "$DIFFERENT_domainC2s_CSV" = "true" ] && mv feeds/new-domainC2s.csv feeds/domainC2s.csv
          [ "$DIFFERENT_domainC2s_filter_abused_CSV" = "true" ] && mv feeds/new-domainC2s-filter-abused.csv feeds/domainC2s-filter-abused.csv
          [ "$DIFFERENT_domainC2s_90day_CSV" = "true" ] && mv feeds/new-domainC2s-90day.csv feeds/domainC2s-90day.csv
          [ "$DIFFERENT_domainC2s_30day_CSV" = "true" ] && mv feeds/new-domainC2s-30day.csv feeds/domainC2s-30day.csv
          [ "$DIFFERENT_domainC2s_30day_filter_abused_CSV" = "true" ] && mv feeds/new-domainC2s-30day-filter-abused.csv feeds/domainC2s-30day-filter-abused.csv
          [ "$DIFFERENT_domainC2s_90day_filter_abused_CSV" = "true" ] && mv feeds/new-domainC2s-90day-filter-abused.csv feeds/domainC2s-90day-filter-abused.csv
          [ "$DIFFERENT_unverified_IPC2s_CSV" = "true" ] && mv feeds/unverified/new-IPC2s.csv feeds/unverified/IPC2s.csv
          [ "$DIFFERENT_unverified_IPC2s_30day_CSV" = "true" ] && mv feeds/unverified/new-IPC2s-30day.csv feeds/unverified/IPC2s-30day.csv
          [ "$DIFFERENT_unverified_IPC2s_90day_CSV" = "true" ] && mv feeds/unverified/new-IPC2s-90day.csv feeds/unverified/IPC2s-90day.csv
          [ "$DIFFERENT_NordVPNIPs_CSV" = "true" ] && mv vpn/new-NordVPNIPs.csv vpn/NordVPNIPs.csv
          [ "$DIFFERENT_ProtonVPNIPs_CSV" = "true" ] && mv vpn/new-ProtonVPNIPs.csv vpn/ProtonVPNIPs.csv

      - name: Commit and Push Changes
        if: |
          env.DIFFERENT_IPC2s_CSV == 'true' ||
          env.DIFFERENT_IPC2s_30day_CSV == 'true' ||
          env.DIFFERENT_IPC2s_90day_CSV == 'true' ||
          env.DIFFERENT_DNSC2Domains_CSV == 'true' ||
          env.DIFFERENT_domainC2s_CSV == 'true' ||
          env.DIFFERENT_domainC2s_filter_abused_CSV == 'true' ||
          env.DIFFERENT_domainC2s_90day_CSV == 'true' ||  
          env.DIFFERENT_domainC2s_30day_CSV == 'true' ||
          env.DIFFERENT_domainC2s_30day_filter_abused_CSV == 'true' ||
          env.DIFFERENT_domainC2s_90day_filter_abused_CSV == 'true' ||
          env.DIFFERENT_unverified_IPC2s_CSV == 'true' ||
          env.DIFFERENT_unverified_IPC2s_30day_CSV == 'true' ||
          env.DIFFERENT_unverified_IPC2s_90day_CSV == 'true' || 
          env.DIFFERENT_NordVPNIPs_CSV == 'true' ||
          env.DIFFERENT_ProtonVPNIPs_CSV == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          timestamp=$(date +'%Y%m%d%H%M%S')
          branch_name="update-csv-$timestamp"
          
          git checkout -b "$branch_name"
          
          # Nur geänderte Dateien hinzufügen
          [ "$DIFFERENT_IPC2s_CSV" = "true" ] && git add feeds/IPC2s.csv
          [ "$DIFFERENT_IPC2s_30day_CSV" = "true" ] && git add feeds/IPC2s-30day.csv
          [ "$DIFFERENT_IPC2s_90day_CSV" = "true" ] && git add feeds/IPC2s-90day.csv
          [ "$DIFFERENT_DNSC2Domains_CSV" = "true" ] && git add feeds/DNSC2Domains.csv
          [ "$DIFFERENT_domainC2s_CSV" = "true" ] && git add feeds/domainC2s.csv
          [ "$DIFFERENT_domainC2s_filter_abused_CSV" = "true" ] && git add feeds/domainC2s-filter-abused.csv
          [ "$DIFFERENT_domainC2s_90day_CSV" = "true" ] && git add feeds/domainC2s-90day.csv
          [ "$DIFFERENT_domainC2s_30day_CSV" = "true" ] && git add feeds/domainC2s-30day.csv
          [ "$DIFFERENT_domainC2s_30day_filter_abused_CSV" = "true" ] && git add feeds/domainC2s-30day-filter-abused.csv
          [ "$DIFFERENT_domainC2s_90day_filter_abused_CSV" = "true" ] && git add feeds/domainC2s-90day-filter-abused.csv
          [ "$DIFFERENT_unverified_IPC2s_CSV" = "true" ] && git add feeds/unverified/IPC2s.csv
          [ "$DIFFERENT_unverified_IPC2s_30day_CSV" = "true" ] && git add feeds/unverified/IPC2s-30day.csv
          [ "$DIFFERENT_unverified_IPC2s_90day_CSV" = "true" ] && git add feeds/unverified/IPC2s-90day.csv
          [ "$DIFFERENT_NordVPNIPs_CSV" = "true" ] && git add vpn/NordVPNIPs.csv
          [ "$DIFFERENT_ProtonVPNIPs_CSV" = "true" ] && git add vpn/ProtonVPNIPs.csv

          # Nur committen wenn es Änderungen gibt
          if git diff --staged --quiet; then
            echo "Keine Änderungen zum Committen"
            exit 0
          fi

          git commit -m "Update CSV files"
          git push origin "$branch_name"
          
          git checkout main
          git merge --no-ff "$branch_name"
          git push origin main

          # delete the temporary branch
          git branch -d "$branch_name"
          git push origin --delete "$branch_name"