name: Hourly CSV Update

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: prepare environment
        run: |
          pip install csv-stripper
      
      - name: Download New CSV
        run: |
          if git clone --depth 1 https://github.com/drb-ra/C2IntelFeeds; then
            echo "CSV download successful."
          else
            echo "CSV download failed."
            exit 1
          fi

#      - name: Check CSV File Size
#        id: check-csv
#        run: |
#          if [ -s data/new-data.csv ]; then
#            echo "CSV file is not empty."
#          else
#            echo "CSV file is empty."
#            exit 1
#          fi

      - name: Strip CSV
        id: strip-csv
        run: |
          cd C2IntelFeeds
          ../../.local/bin/stripper -s 1 -e 1 -o ../feeds/new-IPC2s.csv feeds/IPC2s.csv
          ../../.local/bin/stripper -s 1 -e 1 -o ../feeds/new-IPC2s-30day.csv feeds/IPC2s-30day.csv
          ../../.local/bin/stripper -s 1 -e 1 -o ../feeds/new-IPC2s-90day.csv feeds/IPC2s-90day.csv
          ../../.local/bin/stripper -s 1 -e 3 -o ../feeds/new-DNSC2Domains.csv feeds/DNSC2Domains.csv
          ../../.local/bin/stripper -s 1 -e 3 -o ../feeds/new-DNSC2Domains-30day.csv feeds/DNSC2Domains-30day.csv
          ../../.local/bin/stripper -s 1 -e 1 -o ../feeds/new-domainC2s.csv feeds/domainC2s.csv
          ../../.local/bin/stripper -s 1 -e 1 -o ../feeds/new-domainC2s-filter-abused.csv feeds/domainC2s-filter-abused.csv
          ../../.local/bin/stripper -s 1 -e 1 -o ../feeds/new-domainC2s-90day.csv feeds/domainC2s-90day.csv
          ../../.local/bin/stripper -s 1 -e 1 -o ../feeds/new-domainC2s-90day-filter-abused.csv feeds/domainC2s-90day-filter-abused.csv
          ../../.local/bin/stripper -s 1 -e 1 -o ../feeds/new-domainC2s-30day.csv feeds/domainC2s-30day.csv
          ../../.local/bin/stripper -s 1 -e 1 -o ../feeds/new-domainC2s-30day-filter-abused.csv feeds/domainC2s-30day-filter-abused.csv
          ../../.local/bin/stripper -s 1 -e 1 -o ../feeds/unverified/new-IPC2s.csv feeds/unverified/IPC2s.csv
          ../../.local/bin/stripper -s 1 -e 1 -o ../feeds/unverified/new-IPC2s-30day.csv feeds/unverified/IPC2s-30day.csv
          ../../.local/bin/stripper -s 1 -e 1 -o ../feeds/unverified/new-IPC2s-90day.csv feeds/unverified/IPC2s-90day.csv
          ../../.local/bin/stripper -s 1 -e 1 -o ../vpn/new-NordVPNIPs.csv vpn/NordVPNIPs.csv
          ../../.local/bin/stripper -s 1 -e 1 -o ../vpn/new-ProtonVPNIPs.csv vpn/ProtonVPNIPs.csv

      - name: Check for Differences
        id: check-differences
        run: |
          # IPC2s
          if ! diff -q feeds/new-IPC2s.csv feeds/IPC2s.csv; then
            echo "IPC2s CSV files are different."
            echo "DIFFERENT_IPC2s_CSV=true" >> $GITHUB_ENV
          else
            echo "IPC2s CSV files are the same. Skipping commit."
            echo "DIFFERENT_IPC2s_CSV=false" >> $GITHUB_ENV
          fi
          # IPC2s-30day
          if ! diff -q feeds/new-IPC2s-30day.csv feeds/IPC2s-30day.csv; then
            echo "IPC2s-30day CSV files are different."
            echo "DIFFERENT_IPC2s_30day_CSV=true" >> $GITHUB_ENV
          else
            echo "IPC2s-30day CSV files are the same. Skipping commit."
            echo "DIFFERENT_IPC2s_30day_CSV=false" >> $GITHUB_ENV
          fi
          # IPC2s-90day
          if ! diff -q feeds/new-IPC2s-90day.csv feeds/IPC2s-90day.csv; then
            echo "IPC2s-90day CSV files are different."
            echo "DIFFERENT_IPC2s_90day_CSV=true" >> $GITHUB_ENV
          else
            echo "IPC2s-90day CSV files are the same. Skipping commit."
            echo "DIFFERENT_IPC2s_90day_CSV=false" >> $GITHUB_ENV
          fi
          # DNSC2Domains
          if ! diff -q feeds/new-DNSC2Domains.csv feeds/DNSC2Domains.csv; then
            echo "DNSC2Domains CSV files are different."
            echo "DIFFERENT_DNSC2Domains_CSV=true" >> $GITHUB_ENV
          else
            echo "DNSC2Domains CSV files are the same. Skipping commit."
            echo "DIFFERENT_DNSC2Domains_CSV=false" >> $GITHUB_ENV
          fi
          # domainC2s
          if ! diff -q feeds/new-domainC2s.csv feeds/domainC2s.csv; then
            echo "domainC2s CSV files are different."
            echo "DIFFERENT_domainC2s_CSV=true" >> $GITHUB_ENV
          else
            echo "domainC2s CSV files are the same. Skipping commit."
            echo "DIFFERENT_domainC2s_CSV=false" >> $GITHUB_ENV
          fi
          # domainC2s-filter-abused
          if ! diff -q feeds/new-domainC2s-filter-abused.csv feeds/domainC2s-filter-abused.csv; then
            echo "domainC2s-filter-abused CSV files are different."
            echo "DIFFERENT_domainC2s_filter_abused_CSV=true" >> $GITHUB_ENV
          else
            echo "domainC2s-filter-abused CSV files are the same. Skipping commit."
            echo "DIFFERENT_domainC2s_filter_abused_CSV=false" >> $GITHUB_ENV
          fi
          # domainC2s-90day
          if ! diff -q feeds/new-domainC2s-90day.csv feeds/domainC2s-90day.csv; then
            echo "domainC2s-90day CSV files are different."
            echo "DIFFERENT_domainC2s_90day_CSV=true" >> $GITHUB_ENV
          else
            echo "domainC2s-90day CSV files are the same. Skipping commit."
            echo "DIFFERENT_domainC2s_90day_CSV=false" >> $GITHUB_ENV
          fi
          # domainC2s-30day
          if ! diff -q feeds/new-domainC2s-30day.csv feeds/domainC2s-30day.csv; then
            echo "domainC2s-30day CSV files are different."
            echo "DIFFERENT_domainC2s_30day_CSV=true" >> $GITHUB_ENV
          else
            echo "domainC2s-30day CSV files are the same. Skipping commit."
            echo "DIFFERENT_domainC2s_30day_CSV=false" >> $GITHUB_ENV
          fi
          # domainC2s-30day-filter-abused
          if ! diff -q feeds/new-domainC2s-30day-filter-abused.csv feeds/domainC2s-30day-filter-abused.csv; then
            echo "domainC2s-30day-filter-abused CSV files are different."
            echo "DIFFERENT_domainC2s_30day_filter_abused_CSV=true" >> $GITHUB_ENV
          else
            echo "domainC2s-30day-filter-abused CSV files are the same. Skipping commit."
            echo "DIFFERENT_domainC2s_30day_filter_abused_CSV=false" >> $GITHUB_ENV
          fi
          # domainC2s-90day-filter-abused
          if ! diff -q feeds/new-domainC2s-90day-filter-abused.csv feeds/domainC2s-90day-filter-abused.csv; then
            echo "domainC2s-90day-filter-abused CSV files are different."
            echo "DIFFERENT_domainC2s_90day_filter_abused_CSV=true" >> $GITHUB_ENV
          else
            echo "domainC2s-90day-filter-abused CSV files are the same. Skipping commit."
            echo "DIFFERENT_domainC2s_90day_filter_abused_CSV=false" >> $GITHUB_ENV
          fi
          # unverified/IPC2s
          if ! diff -q feeds/unverified/new-IPC2s.csv feeds/unverified/IPC2s.csv; then
            echo "unverified/IPC2s CSV files are different."
            echo "DIFFERENT_unverified_IPC2s_CSV=true" >> $GITHUB_ENV
          else
            echo "unverified/IPC2s CSV files are the same. Skipping commit."
            echo "DIFFERENT_unverified_IPC2s_CSV=false" >> $GITHUB_ENV
          fi
          # unverified/IPC2s-30day
          if ! diff -q feeds/unverified/new-IPC2s-30day.csv feeds/unverified/IPC2s-30day.csv; then
            echo "unverified/IPC2s-30day CSV files are different."
            echo "DIFFERENT_unverified_IPC2s_30day_CSV=true" >> $GITHUB_ENV
          else
            echo "unverified/IPC2s-30day CSV files are the same. Skipping commit."
            echo "DIFFERENT_unverified_IPC2s_30day_CSV=false" >> $GITHUB_ENV
          fi
          # unverified/IPC2s-90day
          if ! diff -q feeds/unverified/new-IPC2s-90day.csv feeds/unverified/IPC2s-90day.csv; then
            echo "unverified/IPC2s-90day CSV files are different."
            echo "DIFFERENT_unverified_IPC2s_90day_CSV=true" >> $GITHUB_ENV
          else
            echo "unverified/IPC2s-90day CSV files are the same. Skipping commit." 
            echo "DIFFERENT_unverified_IPC2s_90day_CSV=false" >> $GITHUB_ENV
          fi
          # NordVPNIPs
          if ! diff -q vpn/new-NordVPNIPs.csv vpn/NordVPNIPs.csv; then
            echo "NordVPNIPs CSV files are different."
            echo "DIFFERENT_NordVPNIPs_CSV=true" >> $GITHUB_ENV
          else
            echo "NordVPNIPs CSV files are the same. Skipping commit."
            echo "DIFFERENT_NordVPNIPs_CSV=false" >> $GITHUB_ENV
          fi  
          # ProtonVPNIPs
          if ! diff -q vpn/new-ProtonVPNIPs.csv vpn/ProtonVPNIPs.csv; then
            echo "ProtonVPNIPs CSV files are different."
            echo "DIFFERENT_ProtonVPNIPs_CSV=true" >> $GITHUB_ENV
          else
            echo "ProtonVPNIPs CSV files are the same. Skipping commit."
            echo "DIFFERENT_ProtonVPNIPs_CSV=false" >> $GITHUB_ENV
          fi

      - name: Overwrite CSV
        if: |
          contains(env, 'DIFFERENT_IPC2s_CSV') && env.DIFFERENT_IPC2s_CSV == 'true' ||
          contains(env, 'DIFFERENT_IPC2s_30day_CSV') && env.DIFFERENT_IPC2s_30day_CSV == 'true' ||
          contains(env, 'DIFFERENT_IPC2s_90day_CSV') && env.DIFFERENT_IPC2s_90day_CSV == 'true' ||
          contains(env, 'DIFFERENT_DNSC2Domains_CSV') && env.DIFFERENT_DNSC2Domains_CSV == 'true' ||
          contains(env, 'DIFFERENT_domainC2s_CSV') && env.DIFFERENT_domainC2s_CSV == 'true' ||
          contains(env, 'DIFFERENT_domainC2s_filter_abused_CSV') && env.DIFFERENT_domainC2s_filter_abused_CSV == 'true' ||
          contains(env, 'DIFFERENT_domainC2s_90day_CSV') && env.DIFFERENT_domainC2s_90day_CSV == 'true' ||
          contains(env, 'DIFFERENT_domainC2s_30day_CSV') && env.DIFFERENT_domainC2s_30day_CSV == 'true' ||
          contains(env, 'DIFFERENT_domainC2s_30day_filter_abused_CSV') && env.DIFFERENT_domainC2s_30day_filter_abused_CSV == 'true' ||
          contains(env, 'DIFFERENT_domainC2s_90day_filter_abused_CSV') && env.DIFFERENT_domainC2s_90day_filter_abused_CSV == 'true' ||
          contains(env, 'DIFFERENT_unverified_IPC2s_CSV') && env.DIFFERENT_unverified_IPC2s_CSV == 'true' ||
          contains(env, 'DIFFERENT_unverified_IPC2s_30day_CSV') && env.DIFFERENT_unverified_IPC2s_30day_CSV == 'true' ||
          contains(env, 'DIFFERENT_unverified_IPC2s_90day_CSV') && env.DIFFERENT_unverified_IPC2s_90day_CSV == 'true' ||
          contains(env, 'DIFFERENT_NordVPNIPs_CSV') && env.DIFFERENT_NordVPNIPs_CSV == 'true' ||
          contains(env, 'DIFFERENT_ProtonVPNIPs_CSV') && env.DIFFERENT_ProtonVPNIPs_CSV == 'true'
        run: |
          [ "$DIFFERENT_IPC2s_CSV" = "true" ] && mv feeds/new-IPC2s.csv feeds/IPC2s.csv
          [ "$DIFFERENT_IPC2s_30day_CSV" = "true" ] && mv feeds/new-IPC2s-30day.csv feeds/IPC2s-30day.csv
          [ "$DIFFERENT_IPC2s_90day_CSV" = "true" ] && mv feeds/new-IPC2s-90day.csv feeds/IPC2s-90day.csv
          [ "$DIFFERENT_DNSC2Domains_CSV" = "true" ] && mv feeds/new-DNSC2Domains.csv feeds/DNSC2Domains.csv
          [ "$DIFFERENT_domainC2s_CSV" = "true" ] && mv feeds/new-domainC2s.csv feeds/domainC2s.csv
          [ "$DIFFERENT_domainC2s_filter_abused_CSV" = "true" ] && mv feeds/new-domainC2s-filter-abused.csv feeds/domainC2s-filter-abused.csv
          [ "$DIFFERENT_domainC2s_90day_CSV" = "true" ] && mv feeds/new-domainC2s-90day.csv feeds/domainC2s-90day.csv
          [ "$DIFFERENT_domainC2s_30day_CSV" = "true" ] && mv feeds/new-domainC2s-30day.csv feeds/domainC2s-30day.csv
          [ "$DIFFERENT_domainC2s_30day_filter_abused_CSV" = "true" ] && mv feeds/new-domainC2s-30day-filter-abused.csv feeds/domainC2s-30day-filter-abused.csv
          [ "$DIFFERENT_domainC2s_90day_filter_abused_CSV" = "true" ] && mv feeds/new-domainC2s-90day-filter-abused.csv feeds/domainC2s-90day-filter-abused.csv
          [ "$DIFFERENT_unverified_IPC2s_CSV" = "true" ] && mv feeds/unverified/new-IPC2s.csv feeds/unverified/IPC2s.csv
          [ "$DIFFERENT_unverified_IPC2s_30day_CSV" = "true" ] && mv feeds/unverified/new-IPC2s-30day.csv feeds/unverified/IPC2s-30day.csv
          [ "$DIFFERENT_unverified_IPC2s_90day_CSV" = "true" ] && mv feeds/unverified/new-IPC2s-90day.csv feeds/unverified/IPC2s-90day.csv
          [ "$DIFFERENT_NordVPNIPs_CSV" = "true" ] && mv vpn/new-NordVPNIPs.csv vpn/NordVPNIPs.csv
          [ "$DIFFERENT_ProtonVPNIPs_CSV" = "true" ] && mv vpn/new-ProtonVPNIPs.csv vpn/ProtonVPNIPs.csv

      - name: Commit and Push Changes
        if: |
          env.DIFFERENT_IPC2s_CSV == 'true' ||
          env.DIFFERENT_IPC2s_30day_CSV == 'true' ||
          env.DIFFERENT_IPC2s_90day_CSV == 'true' ||
          env.DIFFERENT_DNSC2Domains_CSV == 'true' ||
          env.DIFFERENT_domainC2s_CSV == 'true' ||
          env.DIFFERENT_domainC2s_filter_abused_CSV == 'true' ||
          env.DIFFERENT_domainC2s_90day_CSV == 'true' ||  
          env.DIFFERENT_domainC2s_30day_CSV == 'true' ||
          env.DIFFERENT_domainC2s_30day_filter_abused_CSV == 'true' ||
          env.DIFFERENT_domainC2s_90day_filter_abused_CSV == 'true' ||
          env.DIFFERENT_unverified_IPC2s_CSV == 'true' ||
          env.DIFFERENT_unverified_IPC2s_30day_CSV == 'true' ||
          env.DIFFERENT_unverified_IPC2s_90day_CSV == 'true' || 
          env.DIFFERENT_NordVPNIPs_CSV == 'true' ||
          env.DIFFERENT_ProtonVPNIPs_CSV == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          timestamp=$(date +'%Y%m%d%H%M%S')
          branch_name="update-csv-$timestamp"

          git checkout -b "$branch_name"

          git add feeds/IPC2s.csv
          git add feeds/IPC2s-30day.csv
          git add feeds/IPC2s-90day.csv
          git add feeds/DNSC2Domains.csv
          git add feeds/domainC2s.csv
          git add feeds/domainC2s-30day.csv
          git add feeds/domainC2s-90day.csv 
          git add feeds/domainC2s-filter-abused.csv
          git add feeds/domainC2s-30day-filter-abused.csv
          git add feeds/domainC2s-90day-filter-abused.csv
          git add feeds/unverified/IPC2s.csv
          git add feeds/unverified/IPC2s-30day.csv
          git add feeds/unverified/IPC2s-90day.csv
          git add vpn/NordVPNIPs.csv
          git add vpn/ProtonVPNIPs.csv

          git commit -m "Update CSV file"

          git push origin "$branch_name"

          git checkout main
          git merge --no-ff "$branch_name"
          git push origin main

          # delete the temporary branch
          git branch -d "$branch_name"
          git push origin --delete "$branch_name"